package com.karakept.app.ui.components

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.Icon
import androidx.compose.material3.LocalContentColor
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp

object MaterialIconHelper {
    val allIcons: Map<String, ImageVector> = mapOf(
        // Status & Action
        "Archive" to Icons.Default.Archive,
        "Favorite" to Icons.Default.Favorite,
        "FavoriteBorder" to Icons.Default.FavoriteBorder,
        "Read" to Icons.Default.MarkEmailRead,
        "Unread" to Icons.Default.MarkEmailUnread,
        "Star" to Icons.Default.Star,
        "StarBorder" to Icons.Default.StarBorder,
        "Label" to Icons.Default.Label,
        "Flag" to Icons.Default.Flag,
        "Visibility" to Icons.Default.Visibility,
        "VisibilityOff" to Icons.Default.VisibilityOff,
        "Lock" to Icons.Default.Lock,
        "LockOpen" to Icons.Default.LockOpen,
        "Done" to Icons.Default.Done,
        "DoneAll" to Icons.Default.DoneAll,
        "Schedule" to Icons.Default.Schedule,
        "Error" to Icons.Default.Error,
        "Warning" to Icons.Default.Warning,
        "Verified" to Icons.Default.Verified,
        "NewReleases" to Icons.Default.NewReleases,
        "PriorityHigh" to Icons.Default.PriorityHigh,
        "Unpublished" to Icons.Default.Unpublished,
        "Update" to Icons.Default.Update,
        "History" to Icons.Default.History,
        "Pending" to Icons.Default.Pending,
        "TaskAlt" to Icons.Default.TaskAlt,
        "HourglassEmpty" to Icons.Default.HourglassEmpty,
        "HourglassFull" to Icons.Default.HourglassFull,
        "Check" to Icons.Default.Check,
        "CheckCircle" to Icons.Default.CheckCircle,
        "Info" to Icons.Default.Info,
        "Add" to Icons.Default.Add,
        "Delete" to Icons.Default.Delete,
        "Edit" to Icons.Default.Edit,
        "Settings" to Icons.Default.Settings,
        "Search" to Icons.Default.Search,
        "Share" to Icons.Default.Share,
        "MoreVert" to Icons.Default.MoreVert,
        "Refresh" to Icons.Default.Refresh,
        "Close" to Icons.Default.Close,
        "Menu" to Icons.Default.Menu,
        "Home" to Icons.Default.Home,
        "ArrowBack" to Icons.AutoMirrored.Filled.ArrowBack,
        "ArrowForward" to Icons.AutoMirrored.Filled.ArrowForward,

        // Food & Drink
        "Restaurant" to Icons.Default.Restaurant,
        "LocalCafe" to Icons.Default.LocalCafe,
        "LocalBar" to Icons.Default.LocalBar,
        "Fastfood" to Icons.Default.Fastfood,
        "LocalPizza" to Icons.Default.LocalPizza,
        "Liquor" to Icons.Default.Liquor,
        "Cake" to Icons.Default.Cake,
        "LocalDining" to Icons.Default.LocalDining,
        "BakeryDining" to Icons.Default.BakeryDining,
        "BreakfastDining" to Icons.Default.BreakfastDining,
        "BrunchDining" to Icons.Default.BrunchDining,
        "DinnerDining" to Icons.Default.DinnerDining,
        "IceCream" to Icons.Default.Icecream,
        "LunchDining" to Icons.Default.LunchDining,
        "RamenDining" to Icons.Default.RamenDining,
        "Kitchen" to Icons.Default.Kitchen,
        "EmojiFoodBeverage" to Icons.Default.EmojiFoodBeverage,
        "Coffee" to Icons.Default.Coffee,
        "CoffeeMaker" to Icons.Default.CoffeeMaker,
        "Egg" to Icons.Default.Egg,
        "KebabDining" to Icons.Default.KebabDining,
        "SoupKitchen" to Icons.Default.SoupKitchen,
        "TakeoutDining" to Icons.Default.TakeoutDining,
        "Tapas" to Icons.Default.Tapas,
        "WineBar" to Icons.Default.WineBar,
        "SetMeal" to Icons.Default.SetMeal,

        // Arts & Media
        "CameraAlt" to Icons.Default.CameraAlt,
        "Palette" to Icons.Default.Palette,
        "Brush" to Icons.Default.Brush,
        "MusicNote" to Icons.Default.MusicNote,
        "Headphones" to Icons.Default.Headphones,
        "Movie" to Icons.Default.Movie,
        "Theaters" to Icons.Default.Theaters,
        "Mic" to Icons.Default.Mic,
        "Album" to Icons.Default.Album,
        "Audiotrack" to Icons.Default.Audiotrack,
        "LibraryMusic" to Icons.Default.LibraryMusic,
        "MovieCreation" to Icons.Default.MovieCreation,
        "MusicVideo" to Icons.Default.MusicVideo,
        "Radio" to Icons.Default.Radio,
        "Videocam" to Icons.Default.Videocam,
        "Wallpaper" to Icons.Default.Wallpaper,
        "ArtTrack" to Icons.Default.ArtTrack,
        "AutoStories" to Icons.Default.AutoStories,
        "Book" to Icons.Default.Book,
        "ColorLens" to Icons.Default.ColorLens,
        "Draw" to Icons.Default.Draw,
        "FiberDvr" to Icons.Default.FiberDvr,
        "Film" to Icons.Default.Movie, // Fallback
        "Landscape" to Icons.Default.Landscape,
        "Portrait" to Icons.Default.Portrait,
        "QueueMusic" to Icons.Default.QueueMusic,
        "VideoLibrary" to Icons.Default.VideoLibrary,
        "VolumeUp" to Icons.Default.VolumeUp,
        "Image" to Icons.Default.Image,
        "PlayArrow" to Icons.Default.PlayArrow,

        // Sports & Games
        "SportsEsports" to Icons.Default.SportsEsports,
        "SportsSoccer" to Icons.Default.SportsSoccer,
        "SportsBasketball" to Icons.Default.SportsBasketball,
        "SportsTennis" to Icons.Default.SportsTennis,
        "FitnessCenter" to Icons.Default.FitnessCenter,
        "DirectionsRun" to Icons.Default.DirectionsRun,
        "Pool" to Icons.Default.Pool,
        "SportsBaseball" to Icons.Default.SportsBaseball,
        "SportsCricket" to Icons.Default.SportsCricket,
        "SportsFootball" to Icons.Default.SportsFootball,
        "SportsGolf" to Icons.Default.SportsGolf,
        "SportsHockey" to Icons.Default.SportsHockey,
        "SportsKabaddi" to Icons.Default.SportsKabaddi,
        "SportsMartialArts" to Icons.Default.SportsMartialArts,
        "SportsMotorsports" to Icons.Default.SportsMotorsports,
        "SportsRugby" to Icons.Default.SportsRugby,
        "SportsVolleyball" to Icons.Default.SportsVolleyball,
        "Surfing" to Icons.Default.Surfing,
        "Skateboarding" to Icons.Default.Skateboarding,
        "Snowboarding" to Icons.Default.Snowboarding,
        "Kayaking" to Icons.Default.Kayaking,
        "Kitesurfing" to Icons.Default.Kitesurfing,
        "Rowing" to Icons.Default.Rowing,
        "ScubaDiving" to Icons.Default.ScubaDiving,
        "Sledding" to Icons.Default.Sledding,
        "Snowmobile" to Icons.Default.Snowmobile,
        "Snowshoeing" to Icons.Default.Snowshoeing,
        "SportsBar" to Icons.Default.SportsBar,
        "SportsGymnastics" to Icons.Default.SportsGymnastics,
        "SportsHandball" to Icons.Default.SportsHandball,

        // Tech & Science
        "SmartToy" to Icons.Default.SmartToy,
        "Computer" to Icons.Default.Computer,
        "Code" to Icons.Default.Code,
        "Science" to Icons.Default.Science,
        "Biotech" to Icons.Default.Biotech,
        "Memory" to Icons.Default.Memory,
        "Psychology" to Icons.Default.Psychology,
        "AutoAwesome" to Icons.Default.AutoAwesome,
        "Devices" to Icons.Default.Devices,
        "DeveloperMode" to Icons.Default.DeveloperMode,
        "Dns" to Icons.Default.Dns,
        "Extension" to Icons.Default.Extension,
        "Fingerprint" to Icons.Default.Fingerprint,
        "Keyboard" to Icons.Default.Keyboard,
        "Mouse" to Icons.Default.Mouse,
        "PhoneAndroid" to Icons.Default.PhoneAndroid,
        "Router" to Icons.Default.Router,
        "Security" to Icons.Default.Security,
        "Smartphone" to Icons.Default.Smartphone,
        "Terminal" to Icons.Default.Terminal,
        "AdUnits" to Icons.Default.AdUnits,
        "AddToQueue" to Icons.Default.AddToQueue,
        "AdminPanelSettings" to Icons.Default.AdminPanelSettings,
        "AllInclusive" to Icons.Default.AllInclusive,
        "Android" to Icons.Default.Android,
        "AppShortcut" to Icons.Default.AppShortcut,
        "Architecture" to Icons.Default.Architecture,
        "Backup" to Icons.Default.Backup,
        "BatteryFull" to Icons.Default.BatteryFull,
        "Bluetooth" to Icons.Default.Bluetooth,
        "BugReport" to Icons.Default.BugReport,
        "Build" to Icons.Default.Build,
        "Cable" to Icons.Default.Cable,
        "Cloud" to Icons.Default.Cloud,
        "DataUsage" to Icons.Default.DataUsage,
        "DeveloperBoard" to Icons.Default.DeveloperBoard,
        "DeviceHub" to Icons.Default.DeviceHub,
        "DynamicForm" to Icons.Default.DynamicForm,
        "ElectricBolt" to Icons.Default.ElectricBolt,
        "Engineering" to Icons.Default.Engineering,

        // Society & Economy
        "AttachMoney" to Icons.Default.AttachMoney,
        "TrendingUp" to Icons.Default.TrendingUp,
        "ShowChart" to Icons.Default.ShowChart,
        "Public" to Icons.Default.Public,
        "Groups" to Icons.Default.Groups,
        "School" to Icons.Default.School,
        "Work" to Icons.Default.Work,
        "AccountBalance" to Icons.Default.AccountBalance,
        "Gavel" to Icons.Default.Gavel,
        "Business" to Icons.Default.Business,
        "CardTravel" to Icons.Default.CardTravel,
        "CreditCard" to Icons.Default.CreditCard,
        "Euro" to Icons.Default.Euro,
        "LocalAtm" to Icons.Default.LocalAtm,
        "MonetizationOn" to Icons.Default.MonetizationOn,
        "Paid" to Icons.Default.Paid,
        "Receipt" to Icons.Default.Receipt,
        "ShoppingBag" to Icons.Default.ShoppingBag,
        "ShoppingCart" to Icons.Default.ShoppingCart,
        "Store" to Icons.Default.Store,
        "Apartment" to Icons.Default.Apartment,
        "Badge" to Icons.Default.Badge,
        "BusinessCenter" to Icons.Default.BusinessCenter,
        "Campaign" to Icons.Default.Campaign,
        "CardMembership" to Icons.Default.CardMembership,
        "Cases" to Icons.Default.Cases,
        "Casino" to Icons.Default.Casino,
        "CorporateFare" to Icons.Default.CorporateFare,
        "CurrencyExchange" to Icons.Default.CurrencyExchange,
        "Diversity1" to Icons.Default.Diversity1,
        "Diversity2" to Icons.Default.Diversity2,
        "Diversity3" to Icons.Default.Diversity3,
        "Domain" to Icons.Default.Domain,
        "Factory" to Icons.Default.Factory,
        "Handshake" to Icons.Default.Handshake,
        "Savings" to Icons.Default.Savings,
        "Sell" to Icons.Default.Sell,
        "Storefront" to Icons.Default.Storefront,
        "Wallet" to Icons.Default.Wallet,

        // Travel & Nature
        "Flight" to Icons.Default.Flight,
        "DirectionsCar" to Icons.Default.DirectionsCar,
        "Train" to Icons.Default.Train,
        "TwoWheeler" to Icons.Default.TwoWheeler,
        "LocalFlorist" to Icons.Default.LocalFlorist,
        "Pets" to Icons.Default.Pets,
        "WbSunny" to Icons.Default.WbSunny,
        "NightsStay" to Icons.Default.NightsStay,
        "AcUnit" to Icons.Default.AcUnit,
        "AirplanemodeActive" to Icons.Default.AirplanemodeActive,
        "AirportShuttle" to Icons.Default.AirportShuttle,
        "BeachAccess" to Icons.Default.BeachAccess,
        "Bed" to Icons.Default.Bed,
        "BusAlert" to Icons.Default.BusAlert,
        "Commute" to Icons.Default.Commute,
        "DirectionsBoat" to Icons.Default.DirectionsBoat,
        "DirectionsBus" to Icons.Default.DirectionsBus,
        "DirectionsRailway" to Icons.Default.DirectionsRailway,
        "DirectionsSubway" to Icons.Default.DirectionsSubway,
        "DirectionsTransit" to Icons.Default.DirectionsTransit,
        "ElectricCar" to Icons.Default.ElectricCar,
        "FlightTakeoff" to Icons.Default.FlightTakeoff,
        "Hotel" to Icons.Default.Hotel,
        "LocalGasStation" to Icons.Default.LocalGasStation,
        "LocalHospital" to Icons.Default.LocalHospital,
        "LocalHotel" to Icons.Default.LocalHotel,
        "LocalParking" to Icons.Default.LocalParking,
        "LocalPharmacy" to Icons.Default.LocalPharmacy,
        "LocalShipping" to Icons.Default.LocalShipping,
        "LocalTaxi" to Icons.Default.LocalTaxi,
        "Map" to Icons.Default.Map,
        "Navigation" to Icons.Default.Navigation,
        "NearMe" to Icons.Default.NearMe,
        "Park" to Icons.Default.Park,
        "Terrain" to Icons.Default.Terrain,
        "Traffic" to Icons.Default.Traffic,
        "Tram" to Icons.Default.Tram,
        "Agriculture" to Icons.Default.Agriculture,
        "Airlines" to Icons.Default.Airlines,
        "Anchor" to Icons.Default.Anchor,
        "BikeScooter" to Icons.Default.BikeScooter,
        "Castle" to Icons.Default.Castle,
        "Church" to Icons.Default.Church,
        "ConnectingAirports" to Icons.Default.ConnectingAirports,
        "DepartureBoard" to Icons.Default.DepartureBoard,
        "DirectionsWalk" to Icons.Default.DirectionsWalk,
        "EvStation" to Icons.Default.EvStation,
        "Forest" to Icons.Default.Forest,
        "Grass" to Icons.Default.Grass,
        "Hiking" to Icons.Default.Hiking,
        "Mosque" to Icons.Default.Mosque,
        "Nature" to Icons.Default.Nature,
        "NaturePeople" to Icons.Default.NaturePeople,
        "Sailing" to Icons.Default.Sailing,
        "Subway" to Icons.Default.Subway,
        "Synagogue" to Icons.Default.Synagogue,
        "TempleBuddhist" to Icons.Default.TempleBuddhist,
        "TempleHindu" to Icons.Default.TempleHindu,
        "Volcano" to Icons.Default.Volcano,
        "Water" to Icons.Default.Water,
        "WaterDrop" to Icons.Default.WaterDrop,

        // Home & Lifestyle
        "Chair" to Icons.Default.Chair,
        "DoorFront" to Icons.Default.DoorFront,
        "Light" to Icons.Default.Light,
        "Window" to Icons.Default.Window,
        "Yard" to Icons.Default.Yard,
        "Balcony" to Icons.Default.Balcony,
        "Bathtub" to Icons.Default.Bathtub,
        "Dining" to Icons.Default.Dining,
        "Garage" to Icons.Default.Garage,
        "Living" to Icons.Default.Living,
        "TableBar" to Icons.Default.TableBar,
        "Weekend" to Icons.Default.Weekend,
        "BedroomBaby" to Icons.Default.BedroomBaby,
        "BedroomChild" to Icons.Default.BedroomChild,
        "BedroomParent" to Icons.Default.BedroomParent,
        "Blender" to Icons.Default.Blender,
        "Blinds" to Icons.Default.Blinds,
        "BlindsClosed" to Icons.Default.BlindsClosed,
        "CameraIndoor" to Icons.Default.CameraIndoor,
        "CameraOutdoor" to Icons.Default.CameraOutdoor,
        "ChairAlt" to Icons.Default.ChairAlt,
        "Countertops" to Icons.Default.Countertops,
        "Crib" to Icons.Default.Crib,
        "Deck" to Icons.Default.Deck,
        "DoorBack" to Icons.Default.DoorBack,
        "DoorSliding" to Icons.Default.DoorSliding,
        "Doorbell" to Icons.Default.Doorbell,
        "Fence" to Icons.Default.Fence,
        "Fireplace" to Icons.Default.Fireplace,
        "Flatware" to Icons.Default.Flatware,
        "Foundation" to Icons.Default.Foundation,
        "HeatPump" to Icons.Default.HeatPump,
        "House" to Icons.Default.House,
        "HouseSiding" to Icons.Default.HouseSiding,
        "Iron" to Icons.Default.Iron,
        "KingBed" to Icons.Default.KingBed,
        "Lightbulb" to Icons.Default.Lightbulb,
        "Microwave" to Icons.Default.Microwave,
        "NestCamWiredStand" to Icons.Default.NestCamWiredStand,
        "OutdoorGrill" to Icons.Default.OutdoorGrill,
        "Roofing" to Icons.Default.Roofing,
        "RoomService" to Icons.Default.RoomService,
        "Shower" to Icons.Default.Shower,
        "SingleBed" to Icons.Default.SingleBed,
        "Soap" to Icons.Default.Soap,
        "Stairs" to Icons.Default.Stairs,
        "TableRestaurant" to Icons.Default.TableRestaurant,
        "Umbrella" to Icons.Default.Umbrella,
        "Villa" to Icons.Default.Villa,
        "Wash" to Icons.Default.Wash,
        "WaterDamage" to Icons.Default.WaterDamage,

        // Health & Wellness
        "MonitorHeart" to Icons.Default.MonitorHeart,
        "Healing" to Icons.Default.Healing,
        "Spa" to Icons.Default.Spa,
        "Accessibility" to Icons.Default.Accessibility,
        "CleanHands" to Icons.Default.CleanHands,
        "Coronavirus" to Icons.Default.Coronavirus,
        "Elderly" to Icons.Default.Elderly,
        // Video Games
        "SportsEsports" to Icons.Default.SportsEsports,
        "Gamepad" to Icons.Default.Gamepad,
        "VideogameAsset" to Icons.Default.VideogameAsset,
        "Games" to Icons.Default.Games,
        "Headset" to Icons.Default.Headset,
        "Mouse" to Icons.Default.Mouse,
        "Keyboard" to Icons.Default.Keyboard,
        "Monitor" to Icons.Default.Monitor,
        "Memory" to Icons.Default.Memory,
        "DeveloperBoard" to Icons.Default.DeveloperBoard,

        // Photography
        "Camera" to Icons.Default.Camera,
        "CameraAlt" to Icons.Default.CameraAlt,
        "PhotoCamera" to Icons.Default.PhotoCamera,
        "Photo" to Icons.Default.Photo,
        "PhotoAlbum" to Icons.Default.PhotoAlbum,
        "PhotoLibrary" to Icons.Default.PhotoLibrary,
        "Collections" to Icons.Default.Collections,
        "Image" to Icons.Default.Image,
        "CameraRoll" to Icons.Default.CameraRoll,
        "Movie" to Icons.Default.Movie,
        "MovieCreation" to Icons.Default.MovieCreation,
        "VideoCameraBack" to Icons.Default.VideoCameraBack,
        "Videocam" to Icons.Default.Videocam,
        "Lens" to Icons.Default.Lens,
        "FlashOn" to Icons.Default.FlashOn,
        "HdrOn" to Icons.Default.HdrOn,
        "Panorama" to Icons.Default.Panorama,
        "Portrait" to Icons.Default.Portrait,
        "Landscape" to Icons.Default.Landscape,
        "Filter" to Icons.Default.Filter,
        "FilterVintage" to Icons.Default.FilterVintage,
        "FilterDrama" to Icons.Default.FilterDrama,
        "FilterFrames" to Icons.Default.FilterFrames,
        "Crop" to Icons.Default.Crop,
        "CropFree" to Icons.Default.CropFree,
        "Edit" to Icons.Default.Edit,
        "Brush" to Icons.Default.Brush,
        "Palette" to Icons.Default.Palette,
        "ColorLens" to Icons.Default.ColorLens,

        // History
        "History" to Icons.Default.History,
        "HistoryEdu" to Icons.Default.HistoryEdu,
        "Museum" to Icons.Default.Museum,
        "AccountBalance" to Icons.Default.AccountBalance, // Often used for banks/museums
        "Castle" to Icons.Default.Castle,
        "Church" to Icons.Default.Church,
        "TempleBuddhist" to Icons.Default.TempleBuddhist,
        "TempleHindu" to Icons.Default.TempleHindu,
        "Mosque" to Icons.Default.Mosque,
        "Synagogue" to Icons.Default.Synagogue,
        "Fort" to Icons.Default.Fort, // If available, otherwise skip
        "HourglassEmpty" to Icons.Default.HourglassEmpty,
        "HourglassFull" to Icons.Default.HourglassFull,
        "Schedule" to Icons.Default.Schedule,
        "Timeline" to Icons.Default.Timeline,
        "Update" to Icons.Default.Update,
        "Restore" to Icons.Default.Restore,
        "Book" to Icons.Default.Book,
        "MenuBook" to Icons.Default.MenuBook,
        "ImportContacts" to Icons.Default.ImportContacts, // Looks like a book
        "LibraryBooks" to Icons.Default.LibraryBooks,
        "AutoStories" to Icons.Default.AutoStories,
        "Public" to Icons.Default.Public, // Globe/World history
        "Map" to Icons.Default.Map,
        "Explore" to Icons.Default.Explore,
        "Flag" to Icons.Default.Flag,
        "Campaign" to Icons.Default.Campaign, // Historical events/announcements
        "Gavel" to Icons.Default.Gavel, // Law/History
        "Balance" to Icons.Default.Balance, // Justice/History
        "MedicalServices" to Icons.Default.MedicalServices,
        "Medication" to Icons.Default.Medication,
        "MonitorWeight" to Icons.Default.MonitorWeight,
        "Mood" to Icons.Default.Mood,
        "MoodBad" to Icons.Default.MoodBad,
        "PersonalInjury" to Icons.Default.PersonalInjury,
        "PregnantWoman" to Icons.Default.PregnantWoman,
        "Sanitizer" to Icons.Default.Sanitizer,
        "Sick" to Icons.Default.Sick,
        "Vaccines" to Icons.Default.Vaccines,
        "WheelchairPickup" to Icons.Default.WheelchairPickup,

        // Communication
        "Forum" to Icons.Default.Forum,
        "ChatBubble" to Icons.Default.ChatBubble,
        "Call" to Icons.Default.Call,
        "ContactPhone" to Icons.Default.ContactPhone,
        "ImportContacts" to Icons.Default.ImportContacts,
        "AlternateEmail" to Icons.Default.AlternateEmail,
        "AppRegistration" to Icons.Default.AppRegistration,
        "CallEnd" to Icons.Default.CallEnd,
        "CallMerge" to Icons.Default.CallMerge,
        "CallMissed" to Icons.Default.CallMissed,
        "CallReceived" to Icons.Default.CallReceived,
        "CallSplit" to Icons.Default.CallSplit,
        "CancelPresentation" to Icons.Default.CancelPresentation,
        "CellWifi" to Icons.Default.CellWifi,
        "Chat" to Icons.Default.Chat,
        "ChatBubbleOutline" to Icons.Default.ChatBubbleOutline,
        "CoPresent" to Icons.Default.CoPresent,
        "Comment" to Icons.Default.Comment,
        "CommentsDisabled" to Icons.Default.CommentsDisabled,
        "ContactMail" to Icons.Default.ContactMail,
        "Contacts" to Icons.Default.Contacts,
        "Dialpad" to Icons.Default.Dialpad,
        "DocumentScanner" to Icons.Default.DocumentScanner,
        "DomainVerification" to Icons.Default.DomainVerification,
        "Duo" to Icons.Default.Duo,
        "Email" to Icons.Default.Email,
        "ForwardToInbox" to Icons.Default.ForwardToInbox,
        "Hub" to Icons.Default.Hub,
        "Inbox" to Icons.Default.Inbox,
        "Inventory" to Icons.Default.Inventory,
        "Key" to Icons.Default.Key,
        "Link" to Icons.Default.Link,
        "ListAlt" to Icons.Default.ListAlt,
        "LiveHelp" to Icons.Default.LiveHelp,
        "LocationOff" to Icons.Default.LocationOff,
        "LocationOn" to Icons.Default.LocationOn,
        "Mail" to Icons.Default.Mail,
        "MailLock" to Icons.Default.MailLock,
        "MailOutline" to Icons.Default.MailOutline,
        "MarkChatRead" to Icons.Default.MarkChatRead,
        "MarkChatUnread" to Icons.Default.MarkChatUnread,
        "Message" to Icons.Default.Message,
        "MobileScreenShare" to Icons.Default.MobileScreenShare,
        "MoreTime" to Icons.Default.MoreTime,
        "Nat" to Icons.Default.Nat,
        "NoSim" to Icons.Default.NoSim,
        "NotificationAdd" to Icons.Default.NotificationAdd,
        "Notifications" to Icons.Default.Notifications,
        "NotificationsActive" to Icons.Default.NotificationsActive,
        "NotificationsNone" to Icons.Default.NotificationsNone,
        "NotificationsOff" to Icons.Default.NotificationsOff,
        "NotificationsPaused" to Icons.Default.NotificationsPaused,
        "Outbox" to Icons.Default.Outbox,
        "Phone" to Icons.Default.Phone,
        "PhoneDisabled" to Icons.Default.PhoneDisabled,
        "PhoneEnabled" to Icons.Default.PhoneEnabled,
        "PhoneForwarded" to Icons.Default.PhoneForwarded,
        "PhoneInTalk" to Icons.Default.PhoneInTalk,
        "PhoneIphone" to Icons.Default.PhoneIphone,
        "PhoneLocked" to Icons.Default.PhoneLocked,
        "PhoneMissed" to Icons.Default.PhoneMissed,
        "PhonePaused" to Icons.Default.PhonePaused,
        "Phonelink" to Icons.Default.Phonelink,
        "PhonelinkErase" to Icons.Default.PhonelinkErase,
        "PhonelinkLock" to Icons.Default.PhonelinkLock,
        "PhonelinkOff" to Icons.Default.PhonelinkOff,
        "PhonelinkRing" to Icons.Default.PhonelinkRing,
        "PhonelinkSetup" to Icons.Default.PhonelinkSetup,
        "PortableWifiOff" to Icons.Default.PortableWifiOff,
        "PresentToAll" to Icons.Default.PresentToAll,
        "Print" to Icons.Default.Print,
        "PrintDisabled" to Icons.Default.PrintDisabled,
        "QrCode" to Icons.Default.QrCode,
        "QrCode2" to Icons.Default.QrCode2,
        "QrCodeScanner" to Icons.Default.QrCodeScanner,
        "ReadMore" to Icons.Default.ReadMore,
        "ReceiptLong" to Icons.Default.ReceiptLong,
        "RingVolume" to Icons.Default.RingVolume,
        "RssFeed" to Icons.Default.RssFeed,
        "Rtt" to Icons.Default.Rtt,
        "ScreenShare" to Icons.Default.ScreenShare,
        "Send" to Icons.AutoMirrored.Filled.Send,
        "SendAndArchive" to Icons.Default.SendAndArchive,
        "SendTimeExtension" to Icons.Default.SendTimeExtension,
        "SentimentDissatisfied" to Icons.Default.SentimentDissatisfied,
        "SentimentNeutral" to Icons.Default.SentimentNeutral,
        "SentimentSatisfied" to Icons.Default.SentimentSatisfied,
        "SentimentSatisfiedAlt" to Icons.Default.SentimentSatisfiedAlt,
        "SentimentVeryDissatisfied" to Icons.Default.SentimentVeryDissatisfied,
        "SentimentVerySatisfied" to Icons.Default.SentimentVerySatisfied,
        "SettingsPhone" to Icons.Default.SettingsPhone,
        "ShareLocation" to Icons.Default.ShareLocation,
        "Shortcut" to Icons.Default.Shortcut,
        "SimCard" to Icons.Default.SimCard,
        "SimCardAlert" to Icons.Default.SimCardAlert,
        "Sip" to Icons.Default.Sip,
        "SpeakerNotes" to Icons.Default.SpeakerNotes,
        "SpeakerNotesOff" to Icons.Default.SpeakerNotesOff,
        "SpeakerPhone" to Icons.Default.SpeakerPhone,
        "StayCurrentLandscape" to Icons.Default.StayCurrentLandscape,
        "StayCurrentPortrait" to Icons.Default.StayCurrentPortrait,
        "StayPrimaryLandscape" to Icons.Default.StayPrimaryLandscape,
        "StayPrimaryPortrait" to Icons.Default.StayPrimaryPortrait,
        "StopScreenShare" to Icons.Default.StopScreenShare,
        "SwapCalls" to Icons.Default.SwapCalls,
        "Textsms" to Icons.Default.Textsms,
        "Unsubscribe" to Icons.Default.Unsubscribe,
        "Voicemail" to Icons.Default.Voicemail,
        "VpnKey" to Icons.Default.VpnKey,
        "WifiCalling" to Icons.Default.WifiCalling,
        "WifiCalling3" to Icons.Default.WifiCalling3,

        // General
        "Article" to Icons.AutoMirrored.Filled.Article,
        "Topic" to Icons.Default.Topic,
        "Category" to Icons.Default.Category,
        "Help" to Icons.AutoMirrored.Filled.Help,
        "List" to Icons.AutoMirrored.Filled.List,
        "Note" to Icons.AutoMirrored.Filled.Note,
        "PushPin" to Icons.Default.PushPin,
        "Report" to Icons.Default.Report,
        "Subject" to Icons.Default.Subject,
        "ViewList" to Icons.AutoMirrored.Filled.ViewList,
        "Description" to Icons.Default.Description,
        "Filter" to Icons.Default.FilterList,
        "Sort" to Icons.AutoMirrored.Filled.Sort,
        "Tag" to Icons.Default.Label,
        "Archive" to Icons.Default.Archive,
        "Unarchive" to Icons.Default.Unarchive,
        "Drafts" to Icons.Default.Drafts,
        "Folder" to Icons.Default.Folder,
        "FolderOpen" to Icons.Default.FolderOpen,
        "Place" to Icons.Default.Place,
        "Location" to Icons.Default.LocationOn,
        "Person" to Icons.Default.Person,
        "People" to Icons.Default.People,
        "Group" to Icons.Default.Group,
        "Face" to Icons.Default.Face,
        "AccountCircle" to Icons.Default.AccountCircle,
        "DateRange" to Icons.Default.DateRange,
        "Event" to Icons.Default.Event,
        "Alarm" to Icons.Default.Alarm,
        "Build" to Icons.Default.Build,
        "BugReport" to Icons.Default.BugReport,
        "Lightbulb" to Icons.Default.Lightbulb,
        "Explore" to Icons.Default.Explore
    )

    val categories: Map<String, List<String>> = mapOf(
        "Status" to listOf(
            "Archive", "Favorite", "Read", "Unread", "Star", "Label", "Flag", "Visibility", "Lock", "Done", "Schedule", "Error", "Warning", "Verified", "NewReleases", "PriorityHigh", "Unpublished", "Update", "History", "Pending", "TaskAlt", "HourglassEmpty", "HourglassFull"
        ),
        "General" to listOf(
            "Article", "Book", "Topic", "Category", "Lightbulb", "History", "Help", "Info", "Label", "List", "Note", "PushPin", "Report", "Subject", "ViewList", "Search", "Settings", "Share", "Delete", "Edit", "Add", "Close", "Menu", "Home", "Refresh", "Check", "MoreVert"
        ),
        "Tech" to listOf(
            "SmartToy", "Computer", "Code", "Science", "Biotech", "Memory", "Psychology", "AutoAwesome", "Devices", "DeveloperMode", "Dns", "Extension", "Fingerprint", "Keyboard", "Mouse", "PhoneAndroid", "Router", "Security", "Smartphone", "Terminal", "Android", "Bluetooth", "Cloud", "DataUsage", "Engineering", "WifiCalling"
        ),
        "Food" to listOf(
            "Restaurant", "LocalCafe", "LocalBar", "Fastfood", "LocalPizza", "Liquor", "Cake", "LocalDining", "BakeryDining", "BreakfastDining", "BrunchDining", "DinnerDining", "IceCream", "LunchDining", "RamenDining", "Kitchen", "EmojiFoodBeverage", "Coffee", "CoffeeMaker", "Egg", "KebabDining", "SoupKitchen", "TakeoutDining", "Tapas", "WineBar", "SetMeal"
        ),
        "Arts" to listOf(
            "CameraAlt", "Palette", "Brush", "MusicNote", "Headphones", "Movie", "Theaters", "Mic", "Album", "Audiotrack", "LibraryMusic", "MovieCreation", "MusicVideo", "Radio", "Videocam", "Wallpaper", "ArtTrack", "AutoStories", "Book", "ColorLens", "Draw", "FiberDvr", "Film", "Landscape", "Portrait", "QueueMusic", "VideoLibrary", "VolumeUp", "Image", "PlayArrow"
        ),
        "Sports" to listOf(
            "SportsEsports", "SportsSoccer", "SportsBasketball", "SportsTennis", "FitnessCenter", "DirectionsRun", "Pool", "SportsBaseball", "SportsCricket", "SportsFootball", "SportsGolf", "SportsHockey", "SportsKabaddi", "SportsMartialArts", "SportsMotorsports", "SportsRugby", "SportsVolleyball", "Surfing", "Skateboarding", "Snowboarding", "Kayaking", "Kitesurfing", "Rowing", "ScubaDiving", "Sledding", "Snowmobile", "Snowshoeing", "SportsBar", "SportsGymnastics", "SportsHandball"
        ),
        "Society" to listOf(
            "AttachMoney", "TrendingUp", "ShowChart", "Public", "Groups", "School", "Work", "AccountBalance", "Gavel", "Business", "CardTravel", "CreditCard", "Euro", "LocalAtm", "MonetizationOn", "Paid", "Receipt", "ShoppingBag", "ShoppingCart", "Store", "Apartment", "Badge", "BusinessCenter", "Campaign", "CardMembership", "Cases", "Casino", "CorporateFare", "CurrencyExchange", "Diversity1", "Diversity2", "Diversity3", "Domain", "Factory", "Handshake", "Savings", "Sell", "Storefront", "Wallet"
        ),
        "Travel" to listOf(
            "Flight", "DirectionsCar", "Train", "TwoWheeler", "LocalFlorist", "Landscape", "Pets", "WbSunny", "NightsStay", "AcUnit", "AirplanemodeActive", "AirportShuttle", "BeachAccess", "Bed", "BusAlert", "Commute", "DirectionsBoat", "DirectionsBus", "DirectionsRailway", "DirectionsSubway", "DirectionsTransit", "ElectricCar", "FlightTakeoff", "Hotel", "LocalGasStation", "LocalHospital", "LocalHotel", "LocalParking", "LocalPharmacy", "LocalShipping", "LocalTaxi", "Map", "Navigation", "NearMe", "Park", "Terrain", "Traffic", "Tram", "Castle", "Church", "Forest", "Hiking", "Mosque", "Nature", "Sailing", "Subway", "Synagogue", "TempleBuddhist", "TempleHindu", "Volcano", "Water"
        ),
        "Home" to listOf(
        "Chair", "DoorFront", "Light", "Window", "Yard", "Balcony", "Bathtub", "Dining", "Garage", "Living", "TableBar", "Toilet", "Weekend", "BedroomBaby", "BedroomChild", "BedroomParent", "Blender", "Blinds", "CameraIndoor", "Chandelier", "Countertops", "Crib", "Curtain", "Deck", "Doorbell", "Fence", "Fireplace", "Flatware", "Foundation", "HeatPump", "House", "Iron", "KingBed", "Microwave", "Mop", "OutdoorGrill", "Roofing", "RoomService", "Shower", "SingleBed", "Soap", "Stairs", "TableRestaurant", "Umbrella", "Villa", "Wash", "WaterDamage"
        ),
        "Health" to listOf(
            "MonitorHeart", "Healing", "Spa", "Accessibility", "CleanHands", "Coronavirus", "Elderly", "FaceMask", "HealthAndSafety", "MedicalServices", "Medication", "MonitorWeight", "Mood", "MoodBad", "PersonalInjury", "PregnantWoman", "Sanitizer", "Sick", "Vaccines", "WheelchairPickup"
        ),
        "Video Games" to listOf(
            "SportsEsports", "Gamepad", "VideogameAsset", "Games", "Headset", "Mouse", "Keyboard", "Monitor", "Memory", "DeveloperBoard"
        ),
        "Photography" to listOf(
            "Camera", "CameraAlt", "PhotoCamera", "Photo", "PhotoAlbum", "PhotoLibrary", "Collections", "Image", "CameraRoll",
            "Movie", "MovieCreation", "VideoCameraBack", "Videocam", "Lens", "FlashOn", "HdrOn", "Panorama", "Portrait", "Landscape",
            "Filter", "FilterVintage", "FilterDrama", "FilterFrames", "Crop", "CropFree", "Edit", "Brush", "Palette", "ColorLens"
        ),
        "History" to listOf(
            "History", "HistoryEdu", "Museum", "AccountBalance", "Castle", "Church", "TempleBuddhist", "TempleHindu", "Mosque", "Synagogue",
            "HourglassEmpty", "HourglassFull", "Schedule", "Timeline", "Update", "Restore", "Book", "MenuBook", "ImportContacts",
            "LibraryBooks", "AutoStories", "Public", "Map", "Explore", "Flag", "Campaign", "Gavel", "Balance"
        ),
        "Communication" to listOf(
            "Forum", "ChatBubble", "Call", "ContactPhone", "ImportContacts", "AlternateEmail", "AppRegistration", "CallEnd", "Chat", "Comment", "ContactMail", "Contacts", "Dialpad", "Email", "ForwardToInbox", "Inbox", "Message", "MobileScreenShare", "Notifications", "Phone", "QrCode", "RssFeed", "Send", "ShareLocation", "Sms", "SpeakerNotes", "Textsms", "Voicemail", "WifiCalling"
        )
    )
}

@Composable
fun FilterIcon(
    iconName: String,
    modifier: Modifier = Modifier,
    tint: Color = LocalContentColor.current,
    fontSize: TextUnit = 24.sp
) {
    val icon = MaterialIconHelper.allIcons[iconName]
    if (icon != null) {
        Icon(
            imageVector = icon,
            contentDescription = iconName,
            modifier = modifier,
            tint = tint
        )
    } else {
        // Fallback to text (emoji)
        Text(
            text = iconName,
            modifier = modifier,
            fontSize = fontSize,
            color = tint
        )
    }
}
