blank_issues_enabled: false
contact_links:
  - name: Karakeep (server / backend)
    url: https://github.com/karakeep-app/karakeep/issues
    about: This is the Karakept client app. For issues with the Karakeep server itself, please report them upstream.
